server:
  port: 10536
spring:
  application:
    name: springcloud-bootadmin
  zipkin:
    base-url:
eureka:
  client:
    service-url:
      defaultZone: http://192.168.10.101:10535/eureka
  instance:
    prefer-ip-address: true       #当其他服务获取地址时提供ip而不是hostname
    ip-address: 192.168.10.101    #指定自己的ip信息，不指定的话会自己寻找
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'              #health,info