server:
  port: 10538
spring:
  application:
    name: springcloud-zipkin
  boot:
    admin:
      client:
        url: http://192.168.10.101:10536
  # 解决Zipkin启动The bean 'characterEncodingFilter', defined in
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://192.168.10.101:10535/eureka
  instance:
    prefer-ip-address: true                                 # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 192.168.10.101                              # 指定自己的ip信息，不指定的话会自己寻找
management:
  metrics:
    web:
      # 解决Zipkin报错IllegalArgumentException: Prometheus requires that all meters
      server:
        auto-time-requests: false
