server:
  port: 10535
spring:
  application:
    name: springcloud-eureka
  boot:
    admin:
      client:
        url: http://192.168.10.101:10536
  zipkin:
    base-url: http://192.168.10.101:10538
eureka:
  client:
    register-with-eureka: false         #是否注册自己的信息到eurekaserver，默认是true
    fetch-registry: false               #是否拉取其他服务的信息，默认是true
    service-url:                        #eurekaserver的地址，现在是自己的地址，如果是集群，需要加上其他server的地址
      defaultZone: http://192.168.10.101:${server.port}/eureka